### PR TITLE
upgrade nextjs 15

### PR DESCRIPTION
**Pull request by superlbr**
here https://nextjs.org/blog/next-15-rc#react-19-rc

### CODE REVIEW

**Comment by miurla** [comment]
Thank you for the PR. There is a build error with Vercel, so please check it.
```
Build Failed
Can't parse json file /vercel/path0/package.json: Expected double-quoted property name in JSON at position 1916 while parsing '{ "name": "mophic", "version": "0.1.'
```

Also, this time it's a major update of nextjs, so sufficient testing is necessary. There have been instances where a minor update broke.. https://github.com/miurla/morphic/pull/90

**Comment by superlbr** [comment]
fixed

**Comment by miurla** [comment]
The same build error.

**Comment by superlbr** [comment]
just close because fail to see error detail, and a new one

**Pull request closed without merging**
