### PR TITLE
Refactor retrieveTool to use jina.ai

### PR DESCRIPTION
**Pull request by miurla**
#155 

`jina.ai/reader` will be used instead of exa.ai because it offers a larger free tier and the response isn't bad either.
https://github.com/miurla/morphic/pull/155#issuecomment-2118858686

### CODE REVIEW

**Comment by arsaboo** [comment]
Can you please indicate how to invoke it? Just including a url will automatically work?

**Comment by miurla** [comment]
As long as you use it within the free tier, there is no need to configure anything.

For more details, please check the documentation.
https://jina.ai/reader/#apiform

**Comment by arsaboo** [comment]
I meant, how do we use it in morphic? Just put the url?

**Comment by miurla** [comment]
Just enter the URL and your question. There's an example on morphic.sh, so give it a try.

https://www.morphic.sh/share/XG6wMdV

**Pull request merged**
