### PR TITLE
RAG

### PR DESCRIPTION
**Pull request by ngoiyaeric**
Migrating from redis to ragchat
Implementing upstash ragchat with nextjs ai-sdk. 
Made changes to chat-panel for document/image input and to index.ts

### CODE REVIEW

**Comment by ngoiyaeric** [comment]
/review
--pr_reviewer.extra_instructions="
In the `possible issues` section, emphasize the following:
- Is the code logic efficient?
- ai-sdk model's api base url is encapsulated inside the ai package not sure how ragchat is accessing that from inside nextjs ai sdk, it is there and compatible but innacessible
"
--pr_reviewer.num_code_suggestions="0"
--pr_reviewer.inline_code_comments=true
-i
--pr_reviewer.require_score_review=true
--pr_reviewer.require_can_be_split_review=true
--pr_reviewer.require_soc2_ticket=false

**Comment by miurla** [comment]
@ngoiyaeric Thank you for the pull request. 

However, we are just about to support Local Redis: #303 
We don't want to migrate to Ragchat. We plan to implement RAG separately. 

Thank you for your understanding.

**Comment by miurla** [comment]
Wouldn't it be good to create a pull request in the repository that has forked your morphic?
https://github.com/ngoiyaeric/Morphic/tree/main

**Comment by miurla** [comment]
> Wouldn't it be good to create a pull request in the repository that has forked your morphic?

I will close this PR.

**Pull request closed without merging**
