### PR TITLE
feat(utils): Add Ollama support and improve error handling for models

### PR DESCRIPTION
**Pull request by peperunas**
This PR introduces support for Ollama and also refactors the existing model initialization to improve readability and maintainability.

---

- Added support for Ollama in `lib/utils/index.ts`.
- Modified getModel function to check whether the necessary environment variables are provided.
- Refactored the code inside getModel for better readability and maintainability.
- If Ollama's environmental variables are not set, we fall back to OpenAI.

### CODE REVIEW

**Comment by peperunas** [comment]
I'm still testing the PR - as of now, Tavily seems to be down so I cannot test it any further.

I'll convert it from a draft PR when I'm ready for review / merge.

**Comment by miurla** [comment]
@peperunas It's great that Ollama is usable!

However, there seems to be a issue with Object generation and Tool streaming. Does it seem to work well? It'd be helpful if you could tell me about the models you tested.

https://github.com/sgomez/ollama-ai-provider?tab=readme-ov-file#tested-models-and-capabilities

**Comment by peperunas** [comment]
I was able to test this morning - as Tavily was back online - but there is a blocking issue with Ollama.

Ollama does not support the `tool` role: https://github.com/ollama/ollama/issues/3165. For this reason, once the results are then passed to the Agent, we get an error back:

```
Error: Unsupported role: tool
```

---

image

**Comment by miurla** [comment]
That's good. If Ollama has managed to make the tool calls successfully, it would be good to convert the Tool's message to Assistant before generating the answer. Just yesterday, I turned it into a utility function and merged it into main.

https://github.com/miurla/morphic/blob/main/app/actions.tsx#L168

**Comment by peperunas** [comment]
I see, thanks @miurla.

I set `USE_SPECIFIC_API` to true and removed the hardcoded writer to retrieve the model via `getModel()`; still no luck.

Also, I am confused on the nomenclature: what is a "specific API" in the code?

Anyhow, I guess that - by making the code more robust and less reliant on OpenAI alone - Morphic should start working.

**Comment by miurla** [comment]
I created a draft PR with the commits to your PR. Please check it: #200 

1. Fix the error `Unsupported role: tool`: https://github.com/miurla/morphic/pull/200/commits/2e0edc3da1368e921a90b449188587bf4449e396

2. For tool usage and object generation, `mistral` or `openhermes` is [recommended](https://github.com/sgomez/ollama-ai-provider?tab=readme-ov-file#object-generation), but the text generation was not sufficient. Only for that part, a different model was used as a sub model: https://github.com/miurla/morphic/pull/200/commits/5df77b973ea3abc123c9993d6f1dfa66837f3808

However, it does not operate stably. It will be supported only as an experimental feature.

mistral | mistral & phi3
-- | --
image | image

**Comment by peperunas** [comment]
Closed in favor of #214

**Pull request closed without merging**
