### PR TITLE
Fixed docker related files, added github action workflow

### PR DESCRIPTION
**Pull request by yusing**
- **Updated** dockerfile and docker compose to build a production build instead of running in dev mode
- **Updated** docker compose to use ghcr image
- **Updated** bun lock file which does not match package.json when building docker image with `bun install --frozen-lockfile`
- **Added** GitHub Workflow, now can build docker image and push to ghcr on new tag is pushed
- **Removed** `'6379:6379'` port mapping for redis, since there's no reason to map redis to host
- **Removed** `searxng_data:/data` mount for searxng, since there's no such mountpoint on official searxng's docker compose
- **Refactored** changed `docker-compose.yaml` to `compose.yml` since docker offcially suggest using the latter

### CODE REVIEW

**Comment by miurla** [comment]
@yusing Great work! Thank you. Probably, a build error will occur due to the update of bun.lockb. It has been updated in the latest main, so could you please pull the main branch?

```
[22:20:42.322] Failed to compile.
[22:20:42.322] 
[22:20:42.322] ./components/ui/codeblock.tsx:60:36
[22:20:42.322] Type error: This kind of expression is always truthy.
````

**Comment by miurla** [comment]
@casistack Can you check this PR?

**Comment by miurla** [comment]
Got it. I'll go ahead and close the PR.

**Comment by casistack** [comment]
> @casistack Can you check this PR?

Oop sorry just seen this been away . Glad its fixed :)

**Pull request closed without merging**
