### PR TITLE
Local redis support

### PR DESCRIPTION
**Pull request by casistack**
# Add Local Redis Support

## Motivation
This PR introduces support for local Redis alongside the existing Upstash Redis implementation. This addition aims to enhance development workflows by allowing developers to work with a local Redis instance, reducing dependency on external services during development and testing.

## Summary of Changes
- Implemented a `RedisWrapper` class to abstract Redis operations, supporting both Upstash and local Redis clients.
- Added configuration options to switch between local and Upstash Redis using the `USE_LOCAL_REDIS` environment variable.
- Updated Redis-related functions (`getChats`, `saveChat`, etc.) to work with the new `RedisWrapper`.
- Enhanced error handling and logging for Redis operations to improve debugging and reliability.
- Updated documentation to reflect the new local Redis option.

## Testing Instructions
1. Clone the updated repository and install dependencies.
2. Set up a local Redis instance (instructions in README.md).
3. Copy `.env.example` to `.env` and set `USE_LOCAL_REDIS=true`.
4. Modify docker-compose.yaml to use Dockerfile.test instead of Dockerfile
5. Run the application and perform the following tests:
   - Create a new chat/search
   - Verify that the chat history is saved and can be retrieved
   - Perform multiple searches and ensure chat history persists
   - Clear chat history and verify it's removed from Redis
6. Set `USE_LOCAL_REDIS=false` and repeat steps 4-5 to verify Upstash Redis still works as expected.

## Potential Impacts
- No breaking changes to existing functionality.
- Improved development workflow with local Redis option.
- Slight changes to Redis key structures for better compatibility between local and Upstash Redis.

## Additional Notes
- This PR does not modify any core application logic, focusing solely on the Redis implementation.
- Performance impact should be minimal, with potential improvements for local development environments.
- Future considerations may include adding more Redis operations as needed and further optimizing the `RedisWrapper` class.

## Checklist
- [x] Updated README.md with local Redis setup instructions
- [x] Updated .env.example with new environment variables
- [x] Performed manual testing with both local and Upstash Redis
- [x ] Removed unnecessary debug logging used for testing
- [x] Reviewed and updated code comments

Closes #[110] Provide local Redis option

### CODE REVIEW

**Comment by miurla** [comment]
Hi @casistack , Thank you for the pull request!

## Deploy to Vercel

I deployed it on Vercel, but there are errors. It seems that `bun add redis` is necessary.

## Error
```
Failed to compile.
./lib/redis/config.ts
Module not found: Can't resolve 'redis'
```
https://vercel.com/morphic-ai/morphic/2v1P2pJpqgFz3PFyXUkQx5KAM8Za?filter=errors

## Local Build with Docker

I tried testing with Docker, but even with `USE_LOCAL_REDIS` set, it connects to Upstash and results in an error. Is there a problem with your environment?

## Error
```
morphic-1  |  ○ Compiling / ...
morphic-1  |  ✓ Compiled / in 21.8s
morphic-1  | Error: [Upstash Redis] The 'url' property is missing or undefined in your Redis config.
morphic-1  |     at new o (/app/.next/server/chunks/ssr/node_modules_9f757d._.js:10881:27)
morphic-1  |     at /app/.next/server/chunks/ssr/[root of the server]__c891cd._.js:252:15
```


### .env.local
```
USE_LOCAL_REDIS=true
LOCAL_REDIS_URL=redis://redis:6379
UPSTASH_REDIS_REST_URL=
UPSTASH_REDIS_REST_TOKEN=
```

**Comment by casistack** [comment]
Hi There,
I have now added bun add redis. In terms of the docker. As i mentioned  above, you need to chang the docker-compose.yaml to use Dockerfile.test in my repo. Your main Dockerfile clones your repo and i didnt want to change too much of what you already have. Personally, i think it will be better to use my Dockerfile.test as the main Dockerfile as the user will have to clone the repo anyway but wasn't too sure if you cloned the entire repo for a reason. This might be why the .env.local is not being used.

**Comment by miurla** [comment]
> I have now added bun add redis.

Thank you！ The deployment was successful.

>  you need to chang the docker-compose.yaml to use Dockerfile.test in my repo.

I'm sorry, I overlooked this step.

I was able to confirm that it works with both Upstash and Local Redis. Perfect. Thank you for your excellent work. As you pointed out, let's make Dockerfile.test the main Dockerfile. I will merge this PR once that change is made.

**Comment by casistack** [comment]
Ok i have made the change to Dockerfile.

**Review by miurla — APPROVED** [review]

**Review by miurla — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
