### PR TITLE
Use PPR for instant homepage response

### PR DESCRIPTION
**Pull request by cramforce**

### CODE REVIEW

**Review by miurla — COMMENTED** [review]
Thank you for the PR!
Is PPR compatible with ai/rsc?  It doesn't stream in the Vercel.  it works fine locally.
Do I need to change the Vercel settings?

Preview: https://vercel.live/open-feedback/morphic-git-fork-cramforce-ppr-morphic-ai.vercel.app

**Comment by cramforce** [comment]
Requested access.

I can look into PPR compat. Actually, if all you do is switch away from edge runtime (which doesn't support static optimization) then it might just become static algothether

**Comment by miurla** [comment]
Access granted.
Project name: morphic

Thank you for your support. It seems that this might be related to the following issue as well: 
https://github.com/miurla/morphic/pull/5#issuecomment-2046767332

**Comment by miurla** [comment]
> There was a bug up until 14.2.2 with streaming + server actions + Node.js that has since been resolved. Thanks for helping pinpoint things here, appreciate it. Should work now, if you want to approve that deployment.

https://github.com/miurla/morphic/pull/5#issuecomment-2100788459

This bug was fixed and merged into main, so I pulled the main branch and checked, but it didn't stream. To apply ppr, it needs to be on canary, and it might be a separate issue.

Using PPR might be too early for our project.

**Comment by miurla** [comment]
@cramforce 
I'll close this PR once. Depending on the status of the PPR, I'll decide whether to merge this PR or to implement it again if necessary. Thank you for your support.

**Pull request closed without merging**
