### PR TITLE
feat: enhance tools to use 'tool' from 'ai' package

### PR DESCRIPTION
**Pull request by kuizuo**
Use the tool function from the 'ai' package to make the TS type smarter

### CODE REVIEW

**Review by miurla — COMMENTED** [review]
Nice! Since `pnpm-lock.yaml` is included, could you use `bun`?

https://github.com/miurla/morphic/pull/237/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bb

**Comment by miurla** [comment]
error: `Unhandled Rejection: Error: .append(): The current value doesn't support appending data.`

The version of the AI SDK has been updated, so we need to fix another error. I'll address it in a separate PR, so let's merge this one once that is done.

**Comment by kuizuo** [comment]
thank you!

**Comment by miurla** [comment]
@kuizuo 
Please pull the main branch as the PR(#240 ) for the AI SDK update has been merged.

**Comment by kuizuo** [comment]
@miurla 
I have updated the dependency to the same version as the main branch.

**Comment by miurla** [comment]
@kuizuo 
Updating dependencies alone is not enough; the errors need to be resolved. Could you merge the main branch(upstream)?

**Review by miurla — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
