### PR TITLE
draft: Update Ollama support 

### PR DESCRIPTION
**Pull request by miurla**
ref: #190 

- Fix the error: `Unsupported role: tool`
- Use the Ollama sub-model

## The model used
- OLLAMA_MODEL: `mistral`
- OLLAMA_SUB_MODEL: `phi3`

### CODE REVIEW

**Comment by peperunas** [comment]
Thank you for your work @miurla! Unfortunately, as you said, this is very unstable and I was not able to get Ollama working.

I tried different models but - one way or the other - I cannot get any result back. I guess we need to way for a fix upstream.

**Comment by arsaboo** [comment]
How are https://github.com/rashadphz/farfalle and https://github.com/ItzCrazyKns/Perplexica able to achieve this? Both support Ollama and work very well.

**Comment by miurla** [comment]
@peperunas Thank you for checking.

>  I guess we need to way for a fix upstream.

Yes, to work stably with Ollama, a fix in the upstream is necessary. Since it cannot be merged into the main, I intend to create an experimental branch so that other developers can test it. I appreciate your work!

**Comment by miurla** [comment]
@arsaboo Those projects are not Generative UI projects.

**Comment by peperunas** [comment]
So, I made a mess and instead of actually pushing here the merges between this branch and `main`, I created another PR 🤦 

Sorry @miurla!

**Pull request closed without merging**
